### ISSUE TITLE
As a user i should be able to enable geolocations 

### ISSUE THREAD

**Issue by StevenHaa** [Earthii/Simple-Camera-SOEN-390#104]
[SP - 5]
[Risk - low]
[Priority - High]

## Task

- [x] Mockup, 1sp - Nathan
- [x] Acceptance test, 1sp - Nathan
- [x] Add geolocation, 3sp - Nathan

**Comment by n2chao** [comment]
## Mockups

![location_mockups](https://user-images.githubusercontent.com/10326583/38103788-56d09102-3355-11e8-8caa-e2db89befda3.png)

**Comment by n2chao** [comment]
PR #123

**Comment by jinfuchen** [comment]
Story description is really good.
Story points, Risk, Priority are all good.
Task breakdown is good.
Mockup is good. Please complete acceptance tests on the table, the test results and status.
