### ISSUE TITLE
As a user, I want to be able scan QR codes

### ISSUE THREAD

**Issue by StevenHaa** [Earthii/Simple-Camera-SOEN-390#107]
Implementation of an icon to toggle into a mode where QR codes can be scanned.

[SP - 11]
[Priority - Medium]
[Risk - Medium]

## Tasks

- [x] Mockup, 1sp - Nathan
- [x] Acceptance test, 1sp - Ethan
- [x] Scan QR code functionality 6sp - Nathan, 3sp - Ethan
- [x] #129 Unit tests - Ethan
- [x] #128 UI tests - Nathan

**Comment by Ea10** [comment]
Will be using Google's Mobile Visions' Barcode API for this feature.

**Comment by n2chao** [comment]
## Mockups ##
![mockup_final](https://user-images.githubusercontent.com/10326583/38595432-c928ddb8-3d19-11e8-87b5-d21d262c6ba7.png)

**Comment by n2chao** [comment]
@Ea10 didn't see that you assigned yourself already and made the mockups, my bad

**Comment by Ea10** [comment]
no worries

**Comment by Ea10** [comment]
Acceptance test:
![image](https://user-images.githubusercontent.com/25261046/38698109-ee0a4736-3e61-11e8-8c9d-1140d829fa89.png)

**Comment by jinfuchen** [comment]
Please add the acceptance tests results to the table.

**Comment by Earthii** [comment]
we underestimated this because the library wasn't handling the QR properly

**Comment by Ea10** [comment]
#138

**Comment by n2chao** [comment]
PR #138
