### ISSUE TITLE
As a user, I want to be able to scan a phone number and have it add into the user's contacts

### ISSUE THREAD

**Issue by StevenHaa** [Earthii/Simple-Camera-SOEN-390#108]
[SP - 8]
[Priority - High]
[Risk - medium]

## Task

- [x] Mockup, 1sp - Johnny
- [x] Acceptance test, 1sp - Youness
- [x] Recognize / Add number to contacts , 6sp - Youness, Johnny, Steven 
- [x] #125 Unit tests - Ethan
- [x] #124 UI tests - Ethan

**Comment by younesstawil** [comment]
Should the feature run on very photo taken or have an option to turn it on and off ? If Yes should the button be on the main screen or in the setting ?

**Comment by nemotime** [comment]
![image](https://user-images.githubusercontent.com/14989693/38376445-93a5c27a-38c6-11e8-9ce0-06359e0ff964.png)
Mockup for Phone Number Recognition

**Comment by nemotime** [comment]
![image](https://user-images.githubusercontent.com/14989693/38376445-93a5c27a-38c6-11e8-9ce0-06359e0ff964.png)
Mockup for Phone Number Recognition

**Comment by nemotime** [comment]
@younesstawil maybe if you long press the screen, the phone # detection algorithm should try to identify any phone numbers in the active preview area

**Comment by n2chao** [comment]
@younesstawil I think it should be on/off with a button on the main screen. When it's on, it shouldn't take a picture and only add to contacts. Johnny's idea is good too.

**Comment by younesstawil** [comment]
For now i will added a on/off with a button on the main screen and a picture will not be taken when the mode is on.

**Comment by younesstawil** [comment]
Acceptance Test 108
![acceptance test 108](https://user-images.githubusercontent.com/9422485/38386477-c697e5d4-38e2-11e8-8798-844ee6ea9d9f.PNG)

**Comment by jinfuchen** [comment]
This feature is very good.
Improve the tasks breakdown. Complete the assignees to each task. Create the unit test task and UI test task and add the link to the issues.

**Comment by StevenHaa** [comment]
for some reason the onActivityResult() method isn't being called which means we can't have it run the code to change existing contacts

**Comment by StevenHaa** [comment]
nvm i don't think we need it at all! What i have seem to be working... will do a pr soon after more testing
