### ISSUE TITLE
Update: Old UI Tests

### ISSUE THREAD

**Issue by StevenHaa** [Earthii/Simple-Camera-SOEN-390#110]
Some UI tests from past releases currently fail because of extra code that was added into the activity xml

[SP - 2]
[Risk - Low]
[Priority - High]

## Tasks

Add broken UI tests below:
- [x] "UI test CapturePictureWhileRecordingUITest"
- [x] "UI test FilterIconsUITest"
- [x] "UI test FilterPhotoUITest"
- [x] "UI test RememberLastFilterUITest" 
- [x] "UI test SwipePhotoVideoTest" 
- [x] "UI test TimersIconUITest"

**Comment by StevenHaa** [comment]
i suggest fixing/updating it in milestone 6
