### ISSUE TITLE
UI Testing 

### ISSUE THREAD

**Issue by Earthii** [Earthii/Simple-Camera-SOEN-390#19]
Android studio
Tool bar > run > record espresso test

[SP - 8]
[Risk - Medium]
[Priority - High]

## Tasks

- [x] Testing for filter icons/navigation
- [x] Taking pictures (with filter)
- [x] Remember lastest filter
- [x] Highlight selected filter
- [ ] Update travis to support virtual android devices #54

**Comment by Ea10** [comment]
PR #36

**Comment by Earthii** [comment]
Due to a large amount of time invested to have CI accept UI test, It is postponed to milestone 3
