### ISSUE TITLE
Acceptance Testing

### ISSUE THREAD

**Issue by Ea10** [Earthii/Simple-Camera-SOEN-390#27]
Create acceptance tests for the new feature.

[SP - 3]
[Risk - low]
[Priority - high]

## Tasks

Filter acceptance tests:
- [x] Apply filters
- [x] After opening the filter selection interface, user should be able to scroll between different filters from left to right
- [ ] ~~After closing the filter selection interface, user should not be able to select or scroll between filters anymore~~
- [x] Clicking the same filter multiple times will not break the system
- [x] Invisible button should not trigger filter
- [x] Horizontal should be scrollable on overflow
- [x] filter should be remembered if desired

User story: #9

**Comment by younesstawil** [comment]
started writing the Acceptance Testing on the google doc
