### ISSUE TITLE
Understand existing code

### ISSUE THREAD

**Issue by StevenHaa** [Earthii/Simple-Camera-SOEN-390#3]
Everyone should be able to produce new code for the application.  This is the main point of milestone 1 so that new features may be implemented on milestone 2.

[SP - 3]
[Risk - Medium]
[Priority - High]

## Task
- [x] Learn Kotlin and understand the code - Steven
- [x] Learn Kotlin and understand the code - Eric
- [x] Learn Kotlin and understand the code - Nathan
- [x] Learn Kotlin and understand the code - Ethan
- [x] Learn Kotlin and understand the code - Johnny
- [x] Learn Kotlin and understand the code - Youness
