### ISSUE TITLE
As a user, I should be able to take pictures during a video recording session

### ISSUE THREAD

**Issue by Earthii** [Earthii/Simple-Camera-SOEN-390#50]
there should be an additional button available to take pictures while a video is being recorded to allow the user to take pictures while recording a video

[SP - 8]
[Risk - High]
[Priority - High]

## Tasks

- [x] Acceptance tests 1 SP - Ethan ( In The comments )
- [x] Mock up 2 SP - Johnny #53 
- [x] Take pictures while recording 5 SP - Steven (4), Youness (1)

**Comment by nemotime** [comment]
From issue #53 

![imgwhilerecording](https://user-images.githubusercontent.com/14989693/36657539-07c596f2-1a9b-11e8-8dd4-edb967052249.jpg)

<div>Check icon made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

<div>Shutter icon made by <a href="https://www.flaticon.com/authors/bogdan-rosu" title="Bogdan Rosu">Bogdan Rosu</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

**Comment by Ea10** [comment]
Acceptance test:
![image](https://user-images.githubusercontent.com/25261046/36940237-24fe2f1a-1f0d-11e8-8bcf-f7adbdc2c824.png)
