### ISSUE TITLE
As a user, I should be able to take pictures by smiling

### ISSUE THREAD

**Issue by n2chao** [Earthii/Simple-Camera-SOEN-390#78]
When toggled on, the functionality should locate faces in the viewfinder and take a picture as soon as a smile is detected.

[SP - 13]
[Risk - High]
[Priority - High]

## Tasks

- [x] Acceptance tests, 2 SP - Nathan, Johnny
- [x] Mockups, 2 SP - Nathan
- [x] Take a picture with a smile, 5 SP - Nathan
- [x] Delay before pictures, picture animation - 4 SP - Johnny

**Comment by n2chao** [comment]
### Mockups ###

![smile_mockup](https://user-images.githubusercontent.com/10326583/37373145-bbb87d30-26eb-11e8-84be-6cf3cd896b31.png)

Smile icon from [Google](https://material.io/icons/), licensed under the Apache License Version 2.0.

**Comment by n2chao** [comment]
### Acceptance Test ###

![acceptance_test_smile](https://user-images.githubusercontent.com/10326583/37375006-1c7647a8-26f4-11e8-81b5-e2a79296df9f.PNG)

**Comment by n2chao** [comment]
Alright so I found this  [library by Google](https://developers.google.com/vision/) to have face and smile recognition/detection/tracking.

I plan to use it for this feature. I looked at the sample app they have and I could probably do something similar.

**Comment by StevenHaa** [comment]
Do you know if its going to take a photo if just 1 person in a group smiles, or does it need everyone in the photo to smile?

**Comment by Earthii** [comment]
The library takes a picture after one person smiles,

**Comment by nemotime** [comment]
I changed the way the Smile Detector works, do you mind if I update the acceptance tests? @n2chao

**Comment by n2chao** [comment]
No, go ahead @nemotime

**Comment by n2chao** [comment]
Acceptance tests not updated
