### ISSUE TITLE
Create a button which toggles filters

### ISSUE THREAD

**Issue by Earthii** [Earthii/Simple-Camera-SOEN-390#8]
Create the buttons which triggers visibility of the possible filters

[SP - 8]
[Risk - Medium]
[Priority - High]

## Task

- [x] Add the button @earthii
- [x] Add the filter options buttons @earthii
- [x] Hide the filter buttons on init @StevenHaa 
- [x] make horizontal layout of the filters scrollable @earthii
- [x] add visibility toggle feature @earthii
- [x] ~~Have live preview on filter buttons~~ Impossible with Camera1 API
- [x] add on click event listener for #11 @n2chao 

User story: #9 

## Story point division

@Earthii [6]
@StevenHaa [2]
