### ISSUE TITLE
Unit tests for smile detection feature

### ISSUE THREAD

**Issue by n2chao** [Earthii/Simple-Camera-SOEN-390#80]
[SP - 5]
[Risk - Medium]
[Priority - Medium]

## Task
- [x] (Icon and listener tests) Nathan 
- [ ] (Test Smile Detection activity) Johnny
- [x] (Test FaceTraker) Youness

**Comment by n2chao** [comment]
I made tests for the icon and listener but I'm not sure how to test the actual feature. If you guys have an idea let me know.

**Comment by younesstawil** [comment]
@n2chao I started working on testing the actual feature if you want to take a look. But it is not done it need some tweaking to get it to work.

**Comment by nemotime** [comment]
@younesstawil @n2chao if your unit tests are passing maybe we should merge those first then adjust them to fit the changes to the code I made. If they aren't passing and you don't mind if we rewrite them then maybe accept my PR first before writing the tests.

**Comment by nemotime** [comment]
@n2chao my changes may make the code easier to test... i added more logic and more possibilities for assertions

**Comment by n2chao** [comment]
@nemotime the changes you made won't affect the current tests we have so you can add you tests to my branch or Youness' branch

**Comment by n2chao** [comment]
PR #99
