### ISSUE TITLE
As a User, I should be able to take a square picture

### ISSUE THREAD

**Issue by StevenHaa** [Earthii/Simple-Camera-SOEN-390#81]
When clicked on/toggled on, the screen will display a square area for a photo to be taken

[SP - 11]
[Risk - Medium]
[Priority - High]

## Tasks

- [x] Acceptance tests, 1 SP @StevenHaa 
- [x] Mockups, 2 SP @nemotime 
- [x] Take square photo functionality 6 SP @StevenHaa @Earthii 2SP
- [x] #131 Unit tests - Johnny
- [x] #128 UI tests - Steven

**Comment by Earthii** [comment]
The app already makes the picture into a square by picking a specific resolution. However, the preview is not square... I don't think this would be a proper user story, more like an enhancement

**Comment by StevenHaa** [comment]
Seems like a lot of effort to achieve this feature...(need to go to settings, click on resolutions and then click on the correct square resolution). Maybe we can enhance this experience?

**Comment by nemotime** [comment]
![squareimg](https://user-images.githubusercontent.com/14989693/37552155-bd35f678-2985-11e8-95e3-deddff253f68.png)

**Comment by StevenHaa** [comment]
not sure if we can say this is a user story or not, need to discuss.

**Comment by Earthii** [comment]
we underestimated this since the camera instantiation didn't align with our initial approach

**Comment by StevenHaa** [comment]
PR #137
