### ISSUE TITLE
As a User, I should be able to turn on a grid overlay before taking a photo or recording a video

### ISSUE THREAD

**Issue by StevenHaa** [Earthii/Simple-Camera-SOEN-390#82]
When clicked on/ toggled on, a grid view will appear on the screen 

[SP - 8]
[Risk - Medium]
[Priority - High]

## Tasks

- [x] Acceptance tests, 1 SP [Ethan]
- [x] Mockups, 2 SP [Ethan]
- [x] Grid layout functionality, 2 SP [Ethan]
- [x] Add the grid functionility into the settings activity 3 SP [Eric]

**Comment by Ea10** [comment]
Acceptance Test:
![image](https://user-images.githubusercontent.com/25261046/37494539-a4ad0652-287f-11e8-8090-4446d1307fca.png)

**Comment by Earthii** [comment]
We discussed about this feature and decided the best option is to have this feature in the settings

**Comment by StevenHaa** [comment]
what color should the grid be?

**Comment by Ea10** [comment]
I think white will be good. Is everyone ok with having the grid option appear as one of the fade-in elements when settings is first clicked?

**Comment by Earthii** [comment]
No i think it should be part of the swipe options that is implemented in #84

**Comment by Ea10** [comment]
Will have grid option be in settings

**Comment by Ea10** [comment]
Mockup:
![image](https://user-images.githubusercontent.com/25261046/37571374-2bd67970-2ad2-11e8-9963-4592f273e3c9.png)
Smile icon from [Google](https://material.io/icons/), licensed under the Apache License Version 2.0.

**Comment by StevenHaa** [comment]
We can add it under the settings for now, will there also be an overlay when someones taking a video? Or is it just going to be visible for capturing photos?

**Comment by Ea10** [comment]
Being able to have the grid on during a recording is what made me decide to have it in settings as opposed to having it as a swipe where it’s just one or the other. Grids will be available for videos.

**Comment by Ea10** [comment]
At the moment the grid overlay only works on the Nexus 5. Will add support for other devices

**Comment by Earthii** [comment]
#92

**Comment by Earthii** [comment]
MIssing updated Mockups

**Comment by Ea10** [comment]
Mockups updated. Closing issue
